---
apiVersion: v1
kind: Service
metadata:
  name: myctl
spec:
  selector:
    addon: myctl
  ports:
    - name: myctl
      protocol: TCP
      port: 33081
      targetPort: 33081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addon: myctl
  name: myctl
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: myctl
  template:
    metadata:
      labels:
        addon: myctl
    spec:
      imagePullSecrets: ${IMAGE_PULL_SECRETS}
      containers:
        - command:
            - /myctl
          args:
            - --leader-elect
          image: ${IMAGE_REGISTRY}/erda-addons/myctl:v1.1
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          env:
            - name: HTTP_ADDR
              value: ":33081"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          name: myctl
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: myctl
      terminationGracePeriodSeconds: 10
